trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build Project'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'YourAzureContainerRegistryServiceConnection'
    repository: 'hostingtc.azurecr.io/tech_celestials'
    dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
